#!/bin/bash

alias curl='curl -w "\n"'
alias formatjson='python -mjson.tool'
alias g='git'
alias grep='grep --color'
alias ls='ls -GF'
alias ll='ls -l'
alias screen='screen -U -D -RR'
alias tree='tree -F --dirsfirst -C'
alias zcat='gunzip -c'

# OSX specific
alias here='open .'
alias osascript='arch -i386 osascript'
