#!/bin/bash

alias curl='curl -w "\n"'
alias formatjson='python -mjson.tool'
alias grep='grep --color'
alias ls='ls -GF --color=always'
alias ll='ls -l'
alias psql='psql -x'
alias screen='screen -U -D -RR'
alias tree='tree -F --dirsfirst -C'
alias zcat='gunzip -c'

# OSX specific
alias here='open .'
alias osascript='arch -i386 osascript'

# git
alias g='git'
alias gg='git grep'

# ruby
alias be='bundle exec'

# sift
alias sift="sift --exclude-dirs='.git'"

# neovim by default if exists
if hash nvim 2>/dev/null; then
  alias vim=nvim
fi

alias mosh="mosh -6"

alias tm="tmux attach || tmux new"

