#!/bin/bash

export DOTFILES_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. && pwd )"
export BASHRC_DIR=$DOTFILES_DIR/bash

files=(
  $BASHRC_DIR/options         # Options
  $BASHRC_DIR/exports         # Exports
  $BASHRC_DIR/history         # History setting
  $BASHRC_DIR/aliases         # Aliases
  $BASHRC_DIR/extras          # Extra settings
  $BASHRC_DIR/prompt          # Custom bash prompt
  $HOME/.bash_profile.local   # Local and private settings not under version control (e.g. git credentials)
  $BASHRC_DIR/paths           # Path modifications (must source after `.bash_profile.local` in case of custom `brew` location)
)

# If these files are readable, source them
for file in ${files[@]}; do
  [ -r $file ] && source $file
done

unset files
