#!/bin/bash

export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

export LSCOLORS=gxfxcxdxbxegedabagacad

export EDITOR=vim
export GEM_EDITOR=vim
export BUNDLER_EDITOR=vim

export PROJECTS_PATH=$HOME/code
export GOPATH=$PROJECTS_PATH/go
export XDG_CONFIG_HOME=$HOME/.config

# for tmux
export TMUX_HOSTNAME_BG=colour4
