#!/bin/bash

export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

export LSCOLORS=gxfxcxdxbxegedabagacad

export EDITOR=vim
export GEM_EDITOR=atom
export BUNDLER_EDITOR=atom

export PROJECTS_PATH=$HOME/code
export GOPATH=$PROJECTS_PATH/go
