#!/bin/bash

files=(
  "/opt/boxen/env.sh" # my-boxen env
  "`brew --prefix`/etc/bash_completion" # installed via Homebrew
)

for file in ${files[@]}; do
  [ -r $file ] && source $file
done

unset files
