#!/bin/bash

if hash brew 2>/dev/null; then
  comp_path="`brew --prefix`/etc/bash_completion.d"
  if [ -d $comp_path ]; then
    source "${comp_path}/git-prompt.sh"
    source "${comp_path}/git-completion.bash"
  fi
fi

if hash brew 2>/dev/null; then
  hash rbenv 2>/dev/null && eval "$(rbenv init -)"
fi
if hash nodenv 2>/dev/null; then
  eval "$(nodenv init -)"
fi

function gemcd() {
  local gem_name=$(bundle list | sed -e 's/^ *\* *//g' | peco | cut -d \  -f 1)
  if [ -n "$gem_name" ]; then
    local gem_dir=$(bundle show ${gem_name})
    echo "cd to ${gem_dir}"
    cd $gem_dir
  fi
}

function gemopen() {
  local gem_name=$(bundle list | sed -e 's/^ *\* *//g' | peco | cut -d \  -f 1)
  if [ -n "$gem_name" ]; then
    local gem_dir=$(bundle show ${gem_name})
    vim -c "cd ${gem_dir}" -c "NERDTree"
  fi
}

