#!/bin/bash
dirs_to_prepend=(
  "$HOME/bin"
  "$DOTFILES_DIR/bin"
  "/usr/local/bin" # Ensure that this bin always takes precedence over `/usr/bin`
  "/usr/local/sbin"
)

dirs_to_append=(
  "/usr/bin"
)

for dir in ${dirs_to_prepend[@]}; do
  [ -d $dir ] && PATH="$dir:$PATH"
done

for dir in ${dirs_to_append[@]}; do
  [ -d $dir ] && PATH="$PATH:$dir"
done

unset dirs_to_prepend dirs_to_append
