#!/bin/bash

# converts sernary to ansi 256 color number
function sernary_to_color_num {
  code=`echo 16 + $(( 6#${1} )) | bc`
  echo ${code}
}

# returns ANSI escape code for foreground color
function 256_fg_color {
  if [ -n "$1" ]; then
    num="$1"
  else
    read num
  fi
  echo "\[\033[38;5;${num}m\]"
}

function 16_fg_color {
  if [ -n "$1" ]; then
    num="$1"
  else
    read num
  fi
  echo "\[\033[3${num}m\]"
}

c_host=`16_fg_color 2`
c_path=`16_fg_color 4`
c_git=`16_fg_color 3`
c_end="\[\033[00m\]"

# Enabling git branch indication
if hash __git_ps1 2>/dev/null; then
  export GIT_PS1_SHOWDIRTYSTATE=1
  git_ps1=" \$(__git_ps1 \"⭠ %s \")"
fi

# indicate git branch name
case "$TERM" in
xterm* | screen*)
  leader="‣"
  # PS1="${c_host}\u@\h${c_end}:${c_path}\w${c_end}${c_git}${git_ps1}${c_end}\$ ";;
  PS1="${c_path}\w${c_end}${c_git}${git_ps1}${c_end}${c_host}${leader}${c_end} ";;
*)
  PS1='\u@\h:\w\$ ';;
esac

unset c_user c_host c_path c_end
unset -f 256_fg_color 16_fg_color sernary_to_color_num

