#!/bin/bash

# Source Bash completion (installed via Homebrew)
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

# indicate git branch name
case "$TERM" in
xterm* | screen*)
  PS1='\u@\h:\w$(__git_ps1 "(%s)")\$ ';;
*)
  PS1='\u@\h:\w\$ ';;
esac
